pull_request_rules:
  - name: "Merge Dependabot PRs"
    conditions:
    - author=dependabot[bot]
    - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: squash

