language: python
dist: bionic

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - pypy3

matrix:
  include:
    - python: pypy
      dist: trusty

install:
  - ".travis/install.sh"
before_script: "flake8 hpack test"
script:
  - ".travis/run.sh"

branches:
  only:
    - master
