language: python

sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - pypy

install:
  - ".travis/install.sh"
before_script: "flake8 hpack test"
script:
  - ".travis/run.sh"
